### ISSUE TITLE
access-om2-01 crashing

### ISSUE THREAD

**Issue by aekiss** [marshallward/payu#96] opened 2018-01-30 09:47 UTC
Sorry for the hopelessly vague title.

I've apparently hit a problem in /projects/v45/apps/payu/aek with access-om2-01.
See run dir: `/short/v45/aek156/access-om2/control/01deg_jra55_ryf`.
On the weekend run 29 (job 3477651) crashed after <40min walltime.
archive/restart029 was created but there was no work dir or archive/output029.

see archive/pbs_logs/01deg_jra55_ryf.e3477651:
```
WARNING: no update with \d+ (\d+) \d+ i2o.nc.
WARNING: no update with \d+ (\d+) \d+ o2i.nc.
WARNING: no update with \w{4} \w{4} LAG=\+(\d+).
WARNING: no update with \d+ (\d+) \d+ i2o.nc.
WARNING: no update with \d+ (\d+) \d+ o2i.nc.
WARNING: no update with \w{4} \w{4} LAG=\+(\d+).
Currently Loaded Modulefiles:
  1) payu/aek        2) python/2.7.6    3) openmpi/1.6.3   4) pbs
Traceback (most recent call last):
  File "/jobfs/local/pbs/mom_priv/jobs/3477651.r-man2.SC", line 9, in <module>
    run_cmd.runscript()
  File "/projects/v45/apps/payu/aek/lib/payu/subcommands/run_cmd.py", line 135, in runscript
    expt.archive()
  File "/projects/v45/apps/payu/aek/lib/payu/experiment.py", line 603, in archive
    self.model.archive()
  File "/projects/v45/apps/payu/aek/lib/payu/models/access.py", line 187, in archive
    shutil.copy2(o2i_src, o2i_dst)
  File "/apps/python/2.7.6/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/apps/python/2.7.6/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/short/v45/aek156/access-om2/work/01deg_jra55_ryf/ocean/o2i.nc'
```
I thought there might have been something wrong with run 28, so I re-ran 28 and then tried 29 again today (job 3562946) but it failed in exactly the same way. (I kept the previous restart029 in restart029-3477651)

**Comment by marshallward** [comment] 2018-01-30 11:04
That extra `01deg_jra55_ryf` after `work` seems suspicious.  Is that normally there?  What does `work` normally look like?

Someone who knows more about access-om2 would probably be more useful here.

**Comment by aidanheerdegen** [comment] 2018-01-30 22:33
> That extra 01deg_jra55_ryf after work seems suspicious. Is that normally there? What does work normally look like?

It isn't the local work directory path, but the full path to the temporary directory under `/short`, so that is fine I think.

It reminds me of the errors we got when using symlinks instead of copying, and we'd end up with a huge train of symlinks that broke once the original file was deleted. 

I'll go and try and nut it out when Andrew gets in.

**Comment by nicjhan** [comment] 2018-01-30 22:44
Looking in your access-om2.err you have a CICE crash:

 Warning: Departure points out of bounds in remap
 my_task, i, j =        1039           6          48
 dt, uvel, vvel =    450.000000000000      -8.580390844181061E-002
  -2.04654853162879
 dpx, dpy =   38.6117587988148        920.946839232954
 HTN(i,j), HTN(i+1,j) =   4474.72987222631        4477.22458500369
 HTE(i,j), HTE(i,j+1) =   884.731338755101        885.784346409224
 istep1, my_task, iblk =      459039        1039           1
 Global block:        1040
 Global i and j:        3515        2297
 remap transport: bad departure points

The payu error you are seeing is because payu is trying to archive a crashed run. I'm not sure what that would be. 

I think this CICE error is associated with high ice velocities.... vvel is -2.0 which is perhaps a little high for ice (?).

**Comment by marshallward** [comment] 2018-01-30 22:55
CICE is very poor with return code, right?  Which might partly explain why this was missed, but surely the other models would have also crashed?

Found this MOM warning as well:
```
WARNING from PE   301: diag_manager_mod::send_data_3d: A value for ocean_model in field        wfiform (Min:  -1.13539E-001, Max:   0.00000E+000) is outside the range [ -1.00000E-00       1,  1.00000E-001], and not equal to the missing value.
```
Was this a hung job?  I see nothing but SIGTERM and an MPI_ABORT.

(Thanks for catching that it was in archive Aidan, hopefully I did not confuse the issue)

**Comment by aidanheerdegen** [comment] 2018-01-30 23:10
This suggests it wasn't hung:

```
   Walltime requested: 05:00:00            Walltime Used: 00:40:29
```

**Comment by marshallward** [comment] 2018-01-30 23:34
Thanks Aidan.

I am not actually sure how `mpiexec` handles the exit codes of these MPMD jobs, or what CICE is actually doing here (maybe reporting an error but exiting with code 0?).  Clearly the others are raising SIGTERMs, including other CICE ranks, but somehow payu is ignoring all of this.

There is a long discussion in the manpage about primary and secondary processes, but it clearly says that if a process does not reach MPI_FINALIZE then it returns a nonzero return code.  But it seems clear to me that few (if any) of the models reached this point.

I think at the least we ought to report both zero and nonzero return codes.  At the moment we only report nonzero codes.

**Comment by aekiss** [comment] 2018-02-02 22:56
Hi @nicjhan, where did you find that access-om2.err? As far as I could see, there were no access-om2.* files created by jobs 3477651 or 3562946 in `/short/v45/aek156/access-om2/control/01deg_jra55_ryf` --- should I be looking somewhere else?

**Comment by aekiss** [comment] 2018-02-02 22:58
I have seen this `Departure points out of bounds in remap` error before - it seems to be a CFL type error in CICE and is remedied by reducing the timestep, but we should come up with a better solution. I will raise this as a separate issue.

**Comment by aekiss** [comment] 2018-02-02 23:24
I've resubmitted with dt=300s to see if that helps (dt was 450s). Restart from the last run is now in `restart029-3562946`.

**Comment by aekiss** [comment] 2018-02-03 08:12
Reducing dt from 450 to 300s fixed it: run029 (May-June year 5, job 3685516) seems to have completed with no problems.

So it seems we had a crash due to a CFL problem in CICE but for some reason payu did not handle it correctly (despite handling the same crash correctly in Aug of year 3 and 4 - see https://github.com/OceansAus/access-om2/issues/78).

**Comment by marshallward** [comment] 2018-02-03 08:18
Is this easy to reproduce?  Just pull the default job and set dt to 450?  Or do I need specific restarts?  I'd like to start taking these fails more seriously.

**Comment by aekiss** [comment] 2018-02-03 09:18
Yes, it should be reproducible if you clone /short/v45/aek156/access-om2/control/01deg_jra55_ryf and restart from restart028 (ie do run 29) with dt=450s. I tried it twice and it reproduced.

**Comment by marshallward** [comment] 2018-02-06 05:14
Andrew, I just ran this case and it looks like it crashed due to temperature blowup:
```
FATAL from PE  2626:  Error: temperature out of range with value     6.057846087533E+01 at (i,j,k) = (2033,1446, 24),  (lon,lat,dpt) = (  -76.7500,   19.6529,   97.5708 m)
```
which payu caught and terminated the program.

I am running off commit 5cc80357fb89aad5992a06cab46f4d9465673db2 in `01def_jra55_ryf`, with all the timesteps changed to 450.

**Comment by nicjhan** [comment] 2018-02-07 10:45
Hi @aekiss, perhaps I was looking in the wrong place, looking back this is all I can see: 

[nah599@raijin2 01deg_jra55_ryf]$ pwd
/short/v45/aek156/access-om2/control/01deg_jra55_ryf
[nah599@raijin2 01deg_jra55_ryf]$ find . -name 'access*.err' -print0 | xargs -0 grep 'Departure'
./work-3208848/access-om2.err: Warning: Departure points out of bounds in remap
./work-3322545/access-om2.err: Warning: Departure points out of bounds in remap

**Comment by marshallward** [comment] 2018-10-10 08:40
@aekiss can we close this?  It's not clear to me what the original problem was, or if we'd be able to reproduce it.

**Comment by marshallward** [comment] 2018-10-25 11:04
This issue feels like a spiral of problems.. closing it unless anyone can figures out what was going on.

**Closed by marshallward** 2018-10-25 11:04 UTC
